In [6]:
import pandas as pd

In [7]:
ls  = [
    # 'em_fx_options_long',
    # 'em_fx_spot_forward_long',
    # 'em_interest_rates_long',
    # 'g10_fx_options_long',
    'g10_fx_spot_forward_long',
    # 'g10_interest_rates_long',
    # 'global_risk_long',
    # 'macro_market_proxies_long',
]

ls = [f'{i}.parquet' for i in ls]

tickers = []

In [8]:
for i in ls:
    df = pd.read_parquet(f"../data/raw/{i}")
#     for ticker in df['ticker'].unique():
#         start = df.loc[df['ticker']==ticker]['date'].values[0]
#         end = df.loc[df['ticker']==ticker]['date'].values[-1]
#         len_df = len(df[df['ticker'] == ticker])
#         tickers.append([ticker, start ,end, len_df])
#         print(ticker, start ,end, len_df)

# df = pd.DataFrame(tickers, columns = ['ticker','start','end','size'])

In [26]:
df[df['ticker'] == 'AUD Curncy']

             date      ticker    field   value
0      2007-01-01  AUD Curncy  PX_LAST  0.7894
1      2007-01-01  AUD Curncy   PX_BID  0.7893
2      2007-01-01  AUD Curncy   PX_ASK  0.7895
3      2007-01-02  AUD Curncy  PX_LAST  0.7961
4      2007-01-02  AUD Curncy   PX_BID   0.796
...           ...         ...      ...     ...
15256  2026-06-29  AUD Curncy   PX_BID  0.6884
15257  2026-06-29  AUD Curncy   PX_ASK  0.6889
15258  2026-06-30  AUD Curncy  PX_LAST  0.6919
15259  2026-06-30  AUD Curncy   PX_BID  0.6917
15260  2026-06-30  AUD Curncy   PX_ASK  0.6921

[15261 rows x 4 columns]

In [27]:
df[df['ticker'] == 'AUD3M Curncy']

              date        ticker    field   value
320460  2007-01-01  AUD3M Curncy  PX_LAST  -19.75
320461  2007-01-01  AUD3M Curncy   PX_BID  -19.85
320462  2007-01-01  AUD3M Curncy   PX_ASK  -19.65
320463  2007-01-02  AUD3M Curncy  PX_LAST   -19.9
320464  2007-01-02  AUD3M Curncy   PX_BID   -20.1
...            ...           ...      ...     ...
335716  2026-06-29  AUD3M Curncy   PX_BID  -11.82
335717  2026-06-29  AUD3M Curncy   PX_ASK  -11.44
335718  2026-06-30  AUD3M Curncy  PX_LAST  -11.23
335719  2026-06-30  AUD3M Curncy   PX_BID  -11.46
335720  2026-06-30  AUD3M Curncy   PX_ASK     -11

[15261 rows x 4 columns]

In [10]:
# df.to_csv("outputs/data_timerange.csv", index = None)